apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: API_SERVER_ENDPOINT:6443 # TODO: I can avoid a sed, just use a template
    token: CONTROLLERJOINTOKEN
    caCertHashes: # https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
      - sha256:CAHASH
  timeout: 5m0s
  tlsBootstrapToken: CONTROLLERJOINTOKEN
nodeRegistration:
  taints: null
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd # https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/
