apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
  - token: "${controller_join_token}"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v${k8s_deb_package_version}
apiServer:
  extraArgs:
    profiling: "false"
    enable-admission-plugins: ${enable_admission_plugins} # Default in 1.19
    audit-log-path: "/root/audit.log"
    audit-log-maxage: "30"
    audit-log-maxbackup: "10"
    audit-log-maxsize: "100"
    kubelet-certificate-authority: "/etc/kubernetes/pki/ca.crt"
controllerManager:
  extraArgs:
    profiling: "false"
scheduler:
  extraArgs:
    profiling: "false"