name: Validate terraform
on:
  push:
    branches:
      - '**'
  # https://github.com/hashicorp/setup-terraform
jobs:
  tf:
    name: terraform checks modules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.4
    - run: |
        terraform fmt -check -recursive ./modules
    - name: Terraform Init
      id: init
      run: |
        cd example
        terraform init
    - name: Terraform Validate
      id: validate
      run: |
        cd example
        terraform validate -no-color