name: Validate opentofu
on:
  push:
jobs:
  tf:
    name: opentofu checks modules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.6.2
    - run: |
        tofu fmt -check -recursive ./modules
    - name: tofu Init
      id: init
      run: |
        cd example
        tofu init
    - name: tofu validate
      id: validate
      run: |
        cd example
        tofu validate -no-color